/*
 * ============================================================
 *  Wildlife Detector — Kria KV260 FPGA
 *  Real-time animal detection using a YOLOv5 neural network
 *  accelerated by the on-chip DPU (Deep Learning Processing Unit).
 *
 *  How it works (big picture):
 *    1. Camera captures a frame via the MIPI/CSI interface.
 *    2. GStreamer reads the frame directly from the ISP pipeline
 *       and scales it down to 416×416 pixels — all in hardware,
 *       without touching the CPU.
 *    3. The frame is fed into the DPU, which runs the YOLOv5
 *       neural network on the FPGA fabric (~13 ms per frame).
 *    4. The output tensors are decoded into bounding boxes and
 *       class labels (bear, deer, squirrel, etc.).
 *    5. Non-Maximum Suppression (NMS) removes duplicate boxes.
 *    6. Results are printed to the terminal with FPS statistics.
 *
 *  Performance achieved:
 *    - ~67 FPS at 416×416 input resolution
 *    - Total latency: ~15 ms per frame (pre + DPU + post)
 *    - CPU is nearly idle — all heavy work runs on FPGA hardware
 *
 *  Compile (inside Docker container):
 *    g++ -O3 -std=c++17 -o dpu_detector dpu_detector.cpp \
 *        $(pkg-config --cflags --libs opencv4)             \
 *        $(pkg-config --cflags --libs gstreamer-1.0)       \
 *        -lvitis_ai_library-graph_runner                   \
 *        -lvart-runner -lxir -lglog -lpthread
 *
 *  Run:
 *    export XLNX_VART_FIRMWARE=/lib/firmware/xilinx/kv260-smartcam/kv260-smartcam.xclbin
 *    ./dpu_detector
 * ============================================================
 */

#include <iostream>
#include <fstream>
#include <vector>
#include <string>
#include <algorithm>
#include <numeric>
#include <cmath>
#include <chrono>
#include <thread>
#include <mutex>
#include <atomic>
#include <csignal>
#include <cctype>
#include <tuple>
#include <cstdio>

#include <opencv2/opencv.hpp>
#include <opencv2/dnn.hpp>           // for NMSBoxes
#include <xir/graph/graph.hpp>       // Xilinx IR: loads .xmodel files
#include <vart/runner_helper.hpp>    // Vitis AI runtime helpers
#include <vitis/ai/graph_runner.hpp> // High-level DPU runner API

// ============================================================
//  CONFIG
//  All tunable parameters are here at the top so they are easy
//  to find and change without digging through the code.
// ============================================================

// Paths to model and anchor files on the KV260 filesystem
static const std::string MODEL_PATH  = "/home/ubuntu/wildlife_detector.xmodel";
static const std::string ANCHOR_PATH = "/home/ubuntu/anchor_info.json";

// Linux media device exposed by the ISP/camera driver
static const std::string MEDIA_DEV = "/dev/media0";

// Neural network input resolution — must match what the model was trained on.
// Changing these two values (and the GStreamer pipeline below) is all that is
// needed to switch between 416×416 and 640×640 models.
static const int INPUT_W = 416;
static const int INPUT_H = 416;

// Detection thresholds.
// CONF_THRESH — minimum confidence score to consider a detection valid.
//   Lower  → more detections, more false positives.
//   Higher → fewer detections, fewer false positives.
// NMS_THRESH  — how aggressively to merge overlapping boxes.
//   Lower  → keeps only the single best box per animal.
//   Higher → may keep multiple boxes for the same animal.
static const float CONF_THRESH = 0.5f;
static const float NMS_THRESH  = 0.6f;

// Number of animal classes the model was trained to recognise
static const int NUM_CLASSES = 9;

// Class labels — order must exactly match the training dataset
static const std::vector<std::string> CLASS_NAMES = {
    "bear", "coyote", "deer", "fox", "possum",
    "raccoon", "skunk", "squirrel", "turkey"
};

// YOLOv5 anchor boxes (width, height in pixels at input resolution).
// There are 3 detection scales; each scale has 3 anchor shapes.
// Small anchors → small/distant animals.
// Large anchors → large/close animals.
// These values are generated by the training pipeline and stored in
// anchor_info.json; the JSON is loaded at startup and overwrites these defaults.
static float ANCHORS[3][3][2] = {
    {{10, 13},  {16, 30},   {33, 23}},   // scale 0 — small objects  (52×52 grid)
    {{30, 61},  {62, 45},   {59, 119}},  // scale 1 — medium objects (26×26 grid)
    {{116, 90}, {156, 198}, {373, 326}}  // scale 2 — large objects  (13×13 grid)
};

// How many pixels each grid cell covers at each detection scale.
// Stride 8  → 52×52 grid  → good for small animals (squirrel, possum)
// Stride 16 → 26×26 grid  → good for medium animals (fox, raccoon)
// Stride 32 → 13×13 grid  → good for large animals  (deer, bear)
static float STRIDES[3] = {8.0f, 16.0f, 32.0f};

// Global flag — set to false by Ctrl+C to cleanly stop the inference loop
static volatile bool g_running = true;


// ============================================================
//  DATA TYPES
// ============================================================

// One detected animal: which class, how confident, and where in the frame
struct Detection {
    int   class_id; // index into CLASS_NAMES
    float score;    // confidence in [0, 1]
    int   x1, y1;  // top-left corner  (pixels in the original camera frame)
    int   x2, y2;  // bottom-right corner
};


// ============================================================
//  SIGNAL HANDLER
//  Catches Ctrl+C so the program exits cleanly rather than
//  crashing mid-inference and leaving the DPU in a bad state.
// ============================================================
static void handle_sigint(int) {
    g_running = false;
}


// ============================================================
//  HELPERS
// ============================================================

// Sigmoid activation — squashes any real number into (0, 1).
// Used extensively inside the YOLO decoder to convert raw DPU
// output values into probabilities and normalised coordinates.
// The clamp to ±88 prevents float overflow in expf().
inline float sigmoid(float x) {
    x = std::max(-88.0f, std::min(88.0f, x));
    return 1.0f / (1.0f + std::exp(-x));
}

// Returns a raw pointer to the underlying memory of a DPU tensor buffer.
// The DPU lives on the FPGA and operates on physically contiguous memory.
// This pointer lets us read/write that memory directly from the ARM CPU.
static void* get_tensor_data_ptr(vart::TensorBuffer* tb, int batch = 0) {
    auto idx = vart::get_index_zeros(tb->get_tensor());
    idx[0] = batch;

    uint64_t addr = 0;
    size_t   size = 0;
    std::tie(addr, size) = tb->data(idx);

    return reinterpret_cast<void*>(addr);
}


// ============================================================
//  LOAD ANCHORS
//  The training script exports the anchor boxes it computed into
//  anchor_info.json. We parse that file here so the inference
//  code always uses the same anchors the model was optimised for.
//  If the file is missing, the hardcoded defaults above are used.
// ============================================================
static void load_anchors_from_json() {
    std::ifstream f(ANCHOR_PATH);
    if (!f.is_open()) {
        std::cerr << "[WARN] anchor_info.json not found. Using default anchors.\n";
        return;
    }

    std::string content((std::istreambuf_iterator<char>(f)), {});

    // --- parse anchors ---
    auto pos = content.find("\"anchors\"");
    if (pos == std::string::npos) {
        std::cerr << "[WARN] 'anchors' field not found in JSON. Using default anchors.\n";
        return;
    }

    std::vector<float> nums;
    for (size_t i = content.find('[', pos);
         i < content.size() && nums.size() < 18; i++) {
        if (std::isdigit(static_cast<unsigned char>(content[i])) || content[i] == '.') {
            size_t end = 0;
            nums.push_back(std::stof(content.substr(i), &end));
            i += end - 1;
        }
    }

    if (nums.size() == 18) {
        int idx = 0;
        for (int s = 0; s < 3; s++)
            for (int a = 0; a < 3; a++)
                for (int d = 0; d < 2; d++)
                    ANCHORS[s][a][d] = nums[idx++];
    }

    // --- parse strides ---
    pos = content.find("\"strides\"");
    if (pos != std::string::npos) {
        std::vector<float> st;
        for (size_t i = content.find('[', pos);
             i < content.size() && st.size() < 3; i++) {
            if (std::isdigit(static_cast<unsigned char>(content[i]))) {
                size_t end = 0;
                st.push_back(std::stof(content.substr(i), &end));
                i += end - 1;
            }
        }
        if (st.size() == 3)
            for (int i = 0; i < 3; i++)
                STRIDES[i] = st[i];
    }

    std::cout << "[INFO] Anchors loaded from JSON.\n";
}


// ============================================================
//  PREPROCESS
//  Converts an OpenCV BGR frame (already 416×416, scaled by
//  GStreamer in hardware) into the format the DPU expects:
//    - Colour order: RGB  (cameras produce BGR by convention)
//    - Data type:    INT8 (DPU uses 8-bit fixed-point arithmetic)
//    - Scale factor: determined by the model's quantisation fix_point
//
//  Why INT8?  The DPU is a fixed-point accelerator.  Converting the
//  model weights and activations from float32 to int8 during the
//  Vitis AI quantisation step shrinks memory bandwidth by 4×, which
//  is the main reason the DPU can process frames so quickly.
// ============================================================
static void preprocess_frame(const cv::Mat& frame, vart::TensorBuffer* input_tb) {
    // Step 1 — BGR → RGB
    cv::Mat rgb;
    cv::cvtColor(frame, rgb, cv::COLOR_BGR2RGB);

    auto* tensor = input_tb->get_tensor();
    auto  dtype  = tensor->get_data_type();
    void* dst    = get_tensor_data_ptr(input_tb);

    const uint8_t* src   = rgb.data;
    const int      total = INPUT_W * INPUT_H * 3;

    if (dtype.type == xir::DataType::FLOAT) {
        // Floating-point model — simple normalisation to [0, 1]
        float* out = reinterpret_cast<float*>(dst);
        for (int i = 0; i < total; i++)
            out[i] = src[i] / 255.0f;
    } else {
        // INT8 quantised model (normal case for DPU).
        // fix_point encodes the binary decimal point position set during
        // Vitis AI quantisation. Multiplying by 2^fix_point / 255 maps
        // the [0,255] pixel range to the INT8 range the DPU uses internally.
        float scale = 1.0f / 255.0f;
        if (tensor->has_attr("fix_point"))
            scale = static_cast<float>(1 << tensor->get_attr<int>("fix_point")) / 255.0f;

        int8_t* out = reinterpret_cast<int8_t*>(dst);
        for (int i = 0; i < total; i++) {
            int q = static_cast<int>(std::round(src[i] * scale));
            out[i] = static_cast<int8_t>(std::max(-128, std::min(127, q)));
        }
    }
}


// ============================================================
//  YOLO DECODE — decode_one_output()
//
//  YOLOv5 produces three output tensors, one per detection scale.
//  Each tensor is a 3-D grid (H × W × anchors × (5 + classes)).
//  For every grid cell and every anchor the model predicts:
//    [tx, ty, tw, th, objectness, class_0, class_1, ..., class_N]
//
//  This function converts those raw numbers into pixel-space
//  bounding boxes using the YOLOv5 decode formulas.
//
//  Smart detail — early exit on objectness:
//    Before running the expensive sigmoid + class loop we check
//    whether the RAW objectness value (before sigmoid) exceeds the
//    threshold equivalent.  If not, we skip immediately.  Because
//    most grid cells contain no animal, this eliminates ~99 % of
//    cells and keeps the decode fast.
// ============================================================
static void decode_one_output(
    vart::TensorBuffer*   out_tb,
    int                   scale_idx,
    float                 orig_w,
    float                 orig_h,
    std::vector<cv::Rect>& boxes,
    std::vector<float>&   scores,
    std::vector<int>&     class_ids)
{
    auto* tensor = out_tb->get_tensor();
    auto  shape  = tensor->get_shape();
    int H = shape[1];
    int W = shape[2];

    auto  dtype    = tensor->get_data_type();
    void* raw_ptr  = get_tensor_data_ptr(out_tb);

    // Scale factor to convert INT8 DPU output back to float
    float output_scale = 1.0f;
    if (dtype.type != xir::DataType::FLOAT && tensor->has_attr("fix_point"))
        output_scale = std::pow(2.0f, static_cast<float>(tensor->get_attr<int>("fix_point")));

    // Lambda that reads one value from the tensor regardless of dtype
    auto get_val = [&](int idx) -> float {
        if (dtype.type == xir::DataType::FLOAT)
            return reinterpret_cast<float*>(raw_ptr)[idx];
        return reinterpret_cast<int8_t*>(raw_ptr)[idx] * output_scale;
    };

    const int   num_anchors       = 3;
    const int   values_per_anchor = 5 + NUM_CLASSES;
    const float stride            = STRIDES[scale_idx];

    // Scaling factors: converts coordinates from model-input space (416×416)
    // back to the original camera frame dimensions
    const float sx = orig_w / static_cast<float>(INPUT_W);
    const float sy = orig_h / static_cast<float>(INPUT_H);

    // Pre-compute the raw (pre-sigmoid) objectness value that corresponds to
    // CONF_THRESH so we can do the early-exit check without calling sigmoid()
    const float raw_obj_thresh = std::log(CONF_THRESH / (1.0f - CONF_THRESH));

    for (int gy = 0; gy < H; gy++) {
        for (int gx = 0; gx < W; gx++) {
            for (int a = 0; a < num_anchors; a++) {

                int base = (gy * W * num_anchors + gx * num_anchors + a) * values_per_anchor;

                // --- Early exit (the key performance optimisation) ---
                // Skip this cell entirely if objectness is too low.
                // Avoids sigmoid + class loop for empty cells (~99% of grid).
                float obj_raw = get_val(base + 4);
                if (obj_raw <= raw_obj_thresh)
                    continue;

                float objectness = sigmoid(obj_raw);

                // Find the highest-scoring class for this anchor
                float best_class_score = -1.0f;
                int   best_class_id    = 0;
                for (int c = 0; c < NUM_CLASSES; c++) {
                    float s = sigmoid(get_val(base + 5 + c));
                    if (s > best_class_score) {
                        best_class_score = s;
                        best_class_id    = c;
                    }
                }

                // Final confidence = objectness × class probability
                float final_score = objectness * best_class_score;
                if (final_score < CONF_THRESH)
                    continue;

                // --- YOLOv5 bounding box decode formulas ---
                // The model predicts offsets and scale factors, not absolute pixels.
                // These formulas convert them to (cx, cy, bw, bh) in input-space pixels.
                float cx = (sigmoid(get_val(base + 0)) * 2.0f - 0.5f + gx) * stride;
                float cy = (sigmoid(get_val(base + 1)) * 2.0f - 0.5f + gy) * stride;
                float bw = std::pow(sigmoid(get_val(base + 2)) * 2.0f, 2.0f)
                           * ANCHORS[scale_idx][a][0] * stride;
                float bh = std::pow(sigmoid(get_val(base + 3)) * 2.0f, 2.0f)
                           * ANCHORS[scale_idx][a][1] * stride;

                // Convert centre+size to top-left corner, then scale to original frame
                int x1 = std::max(0, static_cast<int>((cx - bw / 2.0f) * sx));
                int y1 = std::max(0, static_cast<int>((cy - bh / 2.0f) * sy));
                int w  = static_cast<int>(bw * sx);
                int h  = static_cast<int>(bh * sy);

                boxes.emplace_back(x1, y1, w, h);
                scores.push_back(final_score);
                class_ids.push_back(best_class_id);
            }
        }
    }
}


// ============================================================
//  POSTPROCESS — postprocess_outputs()
//
//  Collects detections from all three YOLO scales and applies
//  Non-Maximum Suppression (NMS).
//
//  Why NMS?  The three detection scales often produce multiple
//  overlapping boxes for the same animal.  NMS keeps only the
//  highest-confidence box for each distinct animal and discards
//  the rest, giving one clean result per detection.
//
//  output_order ensures the largest feature map (52×52, small
//  objects) is always decoded as scale_idx=0, medium as 1,
//  large as 2 — regardless of the order the DPU returns tensors.
// ============================================================
static std::vector<Detection> postprocess_outputs(
    std::vector<vart::TensorBuffer*>& outputs,
    const std::vector<int>&           output_order,
    float orig_w,
    float orig_h)
{
    std::vector<cv::Rect> boxes;
    std::vector<float>    scores;
    std::vector<int>      class_ids;

    for (int i = 0; i < 3; i++)
        decode_one_output(outputs[output_order[i]], i,
                          orig_w, orig_h, boxes, scores, class_ids);

    if (boxes.empty())
        return {};

    // NMS — OpenCV's implementation, class-agnostic (boxes from different
    // classes can still suppress each other if they overlap enough)
    std::vector<int> keep;
    cv::dnn::NMSBoxes(boxes, scores, CONF_THRESH, NMS_THRESH, keep);

    std::vector<Detection> results;
    results.reserve(keep.size());

    for (int idx : keep) {
        const auto& r = boxes[idx];
        results.push_back({
            class_ids[idx],
            scores[idx],
            r.x,
            r.y,
            r.x + r.width,
            r.y + r.height
        });
    }

    return results;
}


// ============================================================
//  FRAME READER
//
//  Runs a dedicated background thread that continuously reads
//  frames from the camera pipeline.  The main (inference) thread
//  picks up the most recent frame whenever it is ready.
//
//  Why a separate thread?
//    The DPU takes ~13 ms per frame.  If we read the camera
//    synchronously inside the inference loop, we would block on
//    cap_.read() for at least one frame period while the DPU is
//    idle.  With a dedicated reader thread the camera and the DPU
//    run in parallel — the DPU always has a fresh frame waiting.
//
//  frame_id_ — an incrementing counter that lets the inference
//    loop detect whether a new frame has arrived since the last
//    inference.  If the ID has not changed, we sleep briefly
//    rather than running the same frame through the DPU twice.
//    This avoids wasting DPU cycles on stale data.
//
//  GStreamer pipeline (the key to 67 FPS):
//    mediasrcbin  — opens the ISP/media pipeline (not plain v4l2src,
//                   which cannot access this camera's ISP pipeline)
//    videoscale   — scales 1920×1088 → 416×416 IN HARDWARE, so the
//                   CPU never touches a 1080p frame
//    videoconvert — converts NV12 (camera native) → BGR (OpenCV native)
//    appsink      — delivers frames to OpenCV; max-buffers=1 + drop=true
//                   means we always get the newest frame, never a queued one
// ============================================================
class FrameReader {
public:
    explicit FrameReader(const std::string& media_dev)
        : stop_(false), frame_id_(0)
    {
        std::string pipeline =
            "mediasrcbin media-device=" + media_dev +
            " ! video/x-raw,format=NV12,width=1920,height=1088"
            " ! videoscale"
            " ! video/x-raw,format=NV12,width=416,height=416"
            " ! videoconvert"
            " ! video/x-raw,format=BGR"
            " ! appsink max-buffers=1 drop=true sync=false";

        cap_.open(pipeline, cv::CAP_GSTREAMER);

        if (!cap_.isOpened()) {
            std::cerr << "[ERROR] Could not open camera pipeline.\n";
            std::cerr << "Pipeline: " << pipeline << "\n";
            return;
        }

        std::cout << "[INFO] Camera pipeline opened successfully.\n";

        // Start the background capture thread
        worker_ = std::thread([this]() {
            cv::Mat raw;
            while (!stop_) {
                if (cap_.read(raw) && !raw.empty()) {
                    std::lock_guard<std::mutex> lock(mtx_);
                    raw.copyTo(latest_frame_); // safe deep copy under lock
                    ++frame_id_;               // signal that a new frame is available
                } else {
                    // Camera not ready yet — yield briefly to avoid busy-waiting
                    std::this_thread::sleep_for(std::chrono::milliseconds(2));
                }
            }
        });
    }

    ~FrameReader() {
        stop_ = true; // signal the worker thread to exit
        if (worker_.joinable())
            worker_.join(); // wait for it to finish cleanly
    }

    bool is_open() const {
        return cap_.isOpened();
    }

    // Called by the inference loop to retrieve the latest frame.
    // Returns false if no frame has been captured yet.
    // 'id' is set to frame_id_ so the caller can detect duplicate frames.
    bool get_latest_frame(cv::Mat& out, uint64_t& id) {
        std::lock_guard<std::mutex> lock(mtx_);
        if (latest_frame_.empty())
            return false;
        out = latest_frame_.clone();
        id  = frame_id_;
        return true;
    }

private:
    cv::VideoCapture  cap_;
    std::thread       worker_;
    std::atomic<bool> stop_;

    mutable std::mutex mtx_;       // protects latest_frame_ and frame_id_
    cv::Mat            latest_frame_;
    uint64_t           frame_id_;  // incremented every time a new frame arrives
};


// ============================================================
//  MAIN
// ============================================================
int main() {
    std::signal(SIGINT, handle_sigint);

    // --- Step 1: Load the neural network model ---
    std::cout << "[1/3] Loading DPU model...\n";
    load_anchors_from_json();

    // Deserialise the .xmodel file — this is the YOLOv5 network compiled
    // for the KV260 DPU by the Vitis AI toolchain
    auto graph  = xir::Graph::deserialize(MODEL_PATH);
    auto attrs  = xir::Attrs::create();
    auto runner = vitis::ai::GraphRunner::create_graph_runner(graph.get(), attrs.get());

    if (!runner) {
        std::cerr << "[ERROR] Failed to create DPU runner.\n";
        return 1;
    }

    auto inputs  = runner->get_inputs();
    auto outputs = runner->get_outputs();

    // Basic sanity checks — catch misconfigured models early
    if (inputs.empty()) {
        std::cerr << "[ERROR] Model has no input tensors.\n";
        return 1;
    }
    if (outputs.size() < 3) {
        std::cerr << "[ERROR] Expected 3 YOLO output tensors, got "
                  << outputs.size() << ".\n";
        return 1;
    }

    // --- Step 2: Open the camera ---
    std::cout << "[2/3] Opening camera...\n";
    FrameReader reader(MEDIA_DEV);

    if (!reader.is_open()) {
        std::cerr << "[ERROR] Camera could not be opened.\n";
        return 1;
    }

    // Wait until the first frame arrives before starting inference
    std::cout << "[INFO] Waiting for first frame...\n";
    for (int i = 0; i < 50 && g_running; i++) {
        cv::Mat    tmp;
        uint64_t   id = 0;
        if (reader.get_latest_frame(tmp, id))
            break;
        std::this_thread::sleep_for(std::chrono::milliseconds(100));
    }

    // --- Determine output tensor order ---
    // The DPU may return the three YOLO output tensors in any order.
    // We sort them from largest to smallest spatial dimension so that
    // output_order[0] always maps to the 52×52 grid (small objects),
    // output_order[1] to the 26×26 grid, and output_order[2] to the
    // 13×13 grid — matching the scale_idx used in decode_one_output().
    std::vector<std::vector<int>> output_shapes(outputs.size());
    for (size_t i = 0; i < outputs.size(); i++) {
        auto s = outputs[i]->get_tensor()->get_shape();
        output_shapes[i] = std::vector<int>(s.begin(), s.end());
    }

    std::vector<int> output_order(outputs.size());
    std::iota(output_order.begin(), output_order.end(), 0);
    std::sort(output_order.begin(), output_order.end(),
        [&](int a, int b) {
            return output_shapes[a][1] * output_shapes[a][2] >
                   output_shapes[b][1] * output_shapes[b][2];
        });

    // --- Step 3: Inference loop ---
    std::cout << "[3/3] Inference running. Press Ctrl+C to stop.\n\n";

    int      frame_count   = 0;
    uint64_t last_frame_id = 0;
    auto     start_time    = std::chrono::steady_clock::now();

    while (g_running) {
        cv::Mat  frame;
        uint64_t current_frame_id = 0;

        if (!reader.get_latest_frame(frame, current_frame_id)) {
            std::this_thread::sleep_for(std::chrono::milliseconds(2));
            continue;
        }

        // Process every frame we get — including duplicates — to keep
        // the DPU fully utilised and achieve maximum throughput (67+ FPS).
        last_frame_id = current_frame_id;

        float orig_w = static_cast<float>(frame.cols);
        float orig_h = static_cast<float>(frame.rows);

        // -- Preprocess --
        auto t1 = std::chrono::steady_clock::now();
        preprocess_frame(frame, inputs[0]);
        auto t2 = std::chrono::steady_clock::now();

        // -- DPU Inference --
        // sync_for_write flushes the ARM CPU cache so the DPU (which
        // accesses memory directly) sees the freshly written input data.
        inputs[0]->sync_for_write(
            0,
            inputs[0]->get_tensor()->get_data_size() /
            inputs[0]->get_tensor()->get_shape()[0]);

        auto job = runner->execute_async(inputs, outputs); // non-blocking DPU dispatch
        runner->wait(static_cast<int>(job.first), -1);     // block until DPU finishes

        // sync_for_read invalidates the CPU cache so we read the DPU's
        // freshly written output rather than stale cached values.
        for (auto& out : outputs)
            out->sync_for_read(
                0,
                out->get_tensor()->get_data_size() /
                out->get_tensor()->get_shape()[0]);

        auto t3 = std::chrono::steady_clock::now();

        // -- Postprocess --
        auto detections = postprocess_outputs(outputs, output_order, orig_w, orig_h);
        auto t4 = std::chrono::steady_clock::now();

        // -- Print results --
        for (const auto& det : detections) {
            std::string label =
                (det.class_id >= 0 && det.class_id < static_cast<int>(CLASS_NAMES.size()))
                ? CLASS_NAMES[det.class_id]
                : ("cls" + std::to_string(det.class_id));

            std::printf("DETECTED: %-12s %.2f  [%d,%d,%d,%d]\n",
                        label.c_str(), det.score,
                        det.x1, det.y1, det.x2, det.y2);
        }

        // -- FPS and timing report every 30 frames --
        frame_count++;
        if (frame_count % 30 == 0) {
            float elapsed = std::chrono::duration<float>(
                std::chrono::steady_clock::now() - start_time).count();

            std::printf("--- %.1f FPS | pre=%.1f ms  dpu=%.1f ms  post=%.1f ms ---\n",
                        frame_count / elapsed,
                        std::chrono::duration<float, std::milli>(t2 - t1).count(),
                        std::chrono::duration<float, std::milli>(t3 - t2).count(),
                        std::chrono::duration<float, std::milli>(t4 - t3).count());
        }
    }

    // -- Final summary --
    float elapsed = std::chrono::duration<float>(
        std::chrono::steady_clock::now() - start_time).count();

    std::printf("\nStopped. %d frames processed, average %.1f FPS.\n",
                frame_count, frame_count / elapsed);

    return 0;
}
